### ISSUE TITLE
Reaping expired UserSubscription objects

### ISSUE THREAD

**Issue by mpasternacki** [zhaque/django-subscription#1]
When UserSubscription expires, it is not deleted from database.
When user first cancels old UserSubscription and then upgrades or resubscribes, old UserSubscription does not get deleted.

UserSubscription model should get a "cancelled" BooleanField, so it can be reaped after expiration, deleted on upgrade, and properly reactivated ("uncancelled") on resubscription.

**Comment by mpasternacki** [comment]
Fixed on branch devel

**Comment by zhaque** [comment]
Is this in the master? can I close this ticket?

**Comment by mpasternacki** [comment]
Yes, UserSubscription instance should get deleted when it's needed (especially since we use now subscription modification instead of create new subscription / delete old one process).
