### ISSUE TITLE
Rebate unused subscription part on upgrade

### ISSUE THREAD

**Issue by mpasternacki** [zhaque/django-subscription#2]
PayPal's "trial period" feature should be used to charge less for first billing period on upgrade; the rebate should be equal to part of old subscription plan's billing period that is left unused.

**Comment by mpasternacki** [comment]
This requires modification to django-paypal, since django-paypal does not put a1,t1,p1,a2,p2,t2 in PayPal button form.

**Comment by mpasternacki** [comment]
Note to self: remember to handle UserSubscription.expires and rebate correctly on resubscription: set first payment to 0, first period to "until old_us.expires".

**Comment by zhaque** [comment]
Didn't django-paypal accepted your patch? is this in the master? Can I close this ticket?

**Comment by mpasternacki** [comment]
Patch is accepted.  Later we decided that we won't handle rebates, so bug is irrelevant.  Closed as wontfix.
